server:
  port: 0

spring:
  application:
    name: pokemon-type-service

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus