version: '3.8'

services:
  poke-eureka-service:
    container_name: poke-eureka-service
    image: peppermint100/poke-eureka-service:1.0
    ports:
      - "8761:8761"
    networks:
      - app-network
  poke-config-service:
    container_name: poke-config-service
    image: peppermint100/poke-config-service:1.0
    ports:
      - "8888:8888"
    networks:
      - app-network
  poke-gateway-service:
    container_name: poke-gateway-service
    image: peppermint100/poke-gateway-service:1.1
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - poke-eureka-service
      - poke-config-service
  pokemon-type-service:
    container_name: pokemon-type-service
    image: peppermint100/pokemon-type-service:1.2
    networks:
      - app-network
    depends_on:
      - poke-eureka-service
      - poke-config-service
      - poke-gateway-service
      - poke-mysql
  poke-mysql:
    container_name: poke-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pokemon        
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    ports: 
      - "15672:15672"
      - "5672:5672"
      - "15671:15671"
      - "4369:4369"
    networks:
      - app-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
networks:
  app-network:
    driver: bridge