version: '3.8'

services:
  poke-eureka-service:
    container_name: poke-eureka-service
    image: peppermint100/poke-eureka-service:1.0
    ports:
      - "8761:8761"
    networks:
      - app-network

  poke-gateway-service:
    container_name: poke-gateway-service
    image: peppermint100/poke-gateway-service:1.4
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - poke-eureka-service
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  pokemon-type-service:
    container_name: pokemon-type-service
    image: peppermint100/pokemon-type-service:1.8
    networks:
      - app-network
    depends_on:
      - poke-eureka-service
      - poke-gateway-service
      - poke-mysql
      - zookeeper
      - kafka
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      
  pokemon-service:
    container_name: pokemon-service
    image: peppermint100/pokemon-service:1.8
    networks:
      - app-network
    depends_on:
      - poke-eureka-service
      - poke-gateway-service
      - poke-mysql
      - zookeeper
      - kafka
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  poke-mysql:
    container_name: poke-mysql
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pokemon        
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5

  zookeeper:
    container_name: poke-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      app-network:
        ipv4_address: 172.26.0.100

  kafka:
    container_name: poke-kafka
    image: wurstmeister/kafka
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.26.0.101
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: poke-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      app-network:
        ipv4_address: 172.26.0.101

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - app-network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16