version: '3.8'

services:
  poke-eureka-service:
    container_name: poke-eureka-service
    image: peppermint100/poke-eureka-service:1.0
    ports:
      - "8761:8761"
    networks:
      - app-network
  poke-gateway-service:
    container_name: poke-gateway-service
    image: peppermint100/poke-gateway-service:1.6
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - poke-eureka-service
    environment:
      - spring.profiles.active=prod
  pokemon-type-service:
    container_name: pokemon-type-service
    image: peppermint100/pokemon-type-service:1.4
    networks:
      - app-network
    depends_on:
      - poke-eureka-service
      - poke-gateway-service
      - poke-mysql
    environment:
      - spring.profiles.active=prod
  pokemon-service:
    container_name: pokemon-service
    image: peppermint100/pokemon-service:1.1
    networks:
      - app-network
    depends_on:
      - poke-eureka-service
      - poke-gateway-service
      - poke-mysql
    environment:
      - spring.profiles.active=prod
  poke-mysql:
    container_name: poke-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pokemon        
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5

networks:
  app-network:
    driver: bridge