apiVersion: apps/v1
kind: Deployment
metadata:
  name: poke-mysql-deploy
spec:
  selector:
    matchLabels:
      app: poke-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: poke-mysql
    spec:
      containers:
        - name: poke-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: pokemon
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: poke-mysql
spec:
  selector:
    app: poke-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30003
  type: NodePort