apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-type-deploy
spec:
  selector:
    matchLabels:
      app: pokemon-type-app
  replicas: 1
  template:
    metadata:
      labels:
        app: pokemon-type-app
    spec:
      containers:
        - name: pokemon-type-service
          image: peppermint100/pokemon-type-service:k8s-1.3
          imagePullPolicy: Always
          ports:
            - containerPort: 60000
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: POKEMON-TYPE-SERVICE-URL
              valueFrom:
                configMapKeyRef:
                  name: poke-k8s-configmap
                  key: pokemon-type-service-url
            - name: BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  name: poke-k8s-configmap
                  key: bootstrap-servers
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-type-service
spec:
  type: NodePort
  selector:
    app: pokemon-type-app
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 60000
      nodePort: 30001